name: Migrate

on:
  push:
    branches:
      - main

jobs:
  production:
    name: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: npm i

      - name: Run migrations
        run: npm run prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
